PrivateKey: "1234567890"
Network: "mainnet" # mainnet or testnet
RpcUrl: "https://blockstream.info/api" #https://mempool.space/api https://mempool.space/testnet/api
FeePerByte: 5
UtxoAmount: 1000
Etching:
  Rune: "STUDYZY"
  Symbol: "曾"
  Premine: 1000000
  Amount: 1000
  Cap: 20000
#  Divisibility: 0
#  HeightStart: 0
#  HeightEnd: 0
#  HeightOffsetStart: 0
#  HeightOffsetEnd: 0
Mint:
  RuneId: "2609649:946"